#!/bin/bash

# Define the source and destination paths
source_file="/opt/that_is_my_shit/configs/.vimrc"
destination_file="./configs/.vimrc"

# Check if the source file exists
if [ -e "$source_file" ]; then
    # Copy the source file to the destination
    cp "$source_file" "$destination_file"
    echo "Copied $source_file to $destination_file"
else
    echo "Source file $source_file does not exist."
fi
